# fly.toml app configuration file generated for lawciter on 2023-11-07T00:30:14+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lawciter"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
